services:
# Cервис для работы с корзиной пользователя Cart
  cart:
    container_name: appcart-dev
    image: appcart-dev
    platform: linux/amd64
    build:
      context: .
      target: development
      args:
          GOAPP_TOPORT: ${GOAPP_TOPORT}
      dockerfile: Dockerfile_cart
    volumes:
      - goapp:/cart
      - appconfig:/config
      - applogs:/log
    ports:
      - ${GOAPP_FROMPORT}:${GOAPP_TOPORT}
    restart: unless-stopped
#    networks:
#      - dbapp


#networks:
#  dbapp:
#    driver: bridge

volumes:
  appconfig:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "./config"
  applogs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "./log"
  goapp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "./cart"
