FROM golang:1.22 AS development
WORKDIR /cart
ARG GOAPP_TOPORT
COPY ./cart .
RUN go mod download
RUN go install github.com/cespare/reflex@latest
EXPOSE ${GOAPP_TOPORT?goapp_toport_notset}
CMD reflex -r '(\.go$|go\.mod)' go run cmd/main.go  --start-service

FROM golang:1.22 AS builder
ENV GOOS=linux
ENV CGO_ENABLED=0
ENV GOARCH=amd64
WORKDIR /cart
COPY ./cart .
RUN go mod download
WORKDIR /cart/cmd
RUN go build -o /buildapp/cart
WORKDIR /cart

FROM alpine:latest AS production
RUN apk add --no-cache ca-certificates
COPY --from=builder /buildapp/cart /buildapp/cart
EXPOSE 4000
WORKDIR /buildapp
CMD ./cart