{
 "title": "LOMS Service",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Время", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Время ответа базы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "loms_database_requests_time_bucket{le!=\"+Inf\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Запросы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Запросы к прикладам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "loms_requests_total", "legendFormat": "{{handler}}" }
   ]
  },
  {
   "title": "Запросы в базу",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "loms_database_requests_total", "legendFormat": "{{method}} ({{operation}})" }
   ]
  }
 ]
}