// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package sqlc

import (
	"context"
)

const addOrder = `-- name: AddOrder :one
insert into "order" ("id", "user", status, created_at, updated_at)
    values (nextval('order_id_manual_seq') + $1, $2, $3, now(), now())
    returning id
`

type AddOrderParams struct {
	Column1 interface{}
	User    int64
	Status  OrderStatusType
}

func (q *Queries) AddOrder(ctx context.Context, arg AddOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, addOrder, arg.Column1, arg.User, arg.Status)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addOrderItem = `-- name: AddOrderItem :exec
insert into order_item (order_id, sku, count)
    values ($1, $2, $3)
`

type AddOrderItemParams struct {
	OrderID int64
	Sku     int64
	Count   int32
}

func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) error {
	_, err := q.db.Exec(ctx, addOrderItem, arg.OrderID, arg.Sku, arg.Count)
	return err
}

const getOrder = `-- name: GetOrder :one
select id, "user" as user, status, created_at, updated_at 
    from "order" 
    where id = $1 limit 1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItemsByOrderIDs = `-- name: GetOrderItemsByOrderIDs :many
select id, sku, count
    from order_item
    where order_id = $1
`

type GetOrderItemsByOrderIDsRow struct {
	ID    int64
	Sku   int64
	Count int32
}

func (q *Queries) GetOrderItemsByOrderIDs(ctx context.Context, orderID int64) ([]GetOrderItemsByOrderIDsRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderIDs, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsByOrderIDsRow
	for rows.Next() {
		var i GetOrderItemsByOrderIDsRow
		if err := rows.Scan(&i.ID, &i.Sku, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStatus = `-- name: SetStatus :exec
update "order" 
    set status = $2, updated_at = now()
    where id = $1
`

type SetStatusParams struct {
	ID     int64
	Status OrderStatusType
}

func (q *Queries) SetStatus(ctx context.Context, arg SetStatusParams) error {
	_, err := q.db.Exec(ctx, setStatus, arg.ID, arg.Status)
	return err
}
